parameters:
#    easy_access.example.class: Wachme\Bundle\EasyAccessBundle\Example

services:
#    easy_access.example:
#        class: %easy_access.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
