parameters:
    easy_access.target_manager.class: Wachme\Bundle\EasyAccessBundle\Manager\TargetManager

services:
    easy_access.target_manager:
        class: %easy_access.target_manager.class%
        arguments: [@doctrine.orm.entity_manager]
